-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Gegenereerd op: 27 aug 2024 om 14:20
-- Serverversie: 10.4.32-MariaDB
-- PHP-versie: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `web-shop`
--

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `games`
--

CREATE TABLE `games` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(50) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `price` decimal(10,2) UNSIGNED NOT NULL DEFAULT 0.00,
  `aantal` decimal(12,2) NOT NULL,
  `free` varchar(255) NOT NULL,
  `categories` tinyint(10) UNSIGNED NOT NULL DEFAULT 0,
  `image` varchar(255) NOT NULL DEFAULT 'https://placehold.co/500x500',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Gegevens worden geëxporteerd voor tabel `games`
--

INSERT INTO `games` (`id`, `name`, `title`, `description`, `price`, `aantal`, `free`, `categories`, `image`, `created_at`, `updated_at`) VALUES
(1, 'Tomb Raider', '', 'Tomb Raider explores the intense and gritty origin story of Lara Croft and her ascent from a young woman to a hardened survivor. Armed only with raw instincts and the ability to push beyond the limits of human endurance, Lara must fight to unravel the dark history of a forgotten island to escape its relentless hold.', 0.00, 0.00, '', 1, 'tombraider.jpg', '2024-08-24 11:42:20', NULL),
(2, '2 Dying Light 2 Stay Human', '', 'Humanity is fighting a losing battle against the virus. Experience a post-apocalyptic open world overrun by hordes of zombies, where your parkour and combat skills are key to survival. Traverse the City freely during the day, but watch the monsters take over during the night.', 0.00, 0.00, '', 5, '2 Dying Light 2 Stay Human.jpg', '2024-08-24 12:03:06', NULL),
(3, '2 Red Dead Redemption', '', 'The story is set in a fictionalized representation of the United States in 1899 and follows the exploits of Arthur Morgan, an outlaw and member of the Van der Linde gang, who must deal with the decline of the Wild West while attempting to survive against government forces, rival gangs, and other adversaries.', 0.00, 0.00, '', 6, '2 Red Dead Redemption.jpg', '2024-08-24 12:03:06', NULL),
(4, '3 Call of Duty', 'Call of Duty: Black Ops III takes place in 2065, 40 years after the events of Black Ops II, in a world facing upheaval from conflicts, climate change and new technologies. A Third Cold War is ongoing between two global alliances, known as the Winslow Acco', '', 0.00, 0.00, '', 5, '3 Call of Duty.jpg', '2024-08-24 12:03:06', NULL),
(5, 'Battlefield V', '', 'Overview. Battlefield V returns to the major conflict of World War II, with a heightened focus on the lesser known battles of the war. The game is designed to be the most immersive experience in the series, with storylines ranging across major battles of the war.', 0.00, 0.00, '', 5, '815OuvyY30L.jpg', '2024-08-24 12:03:06', NULL),
(6, 'Cyberpunk 2077', '', 'Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a dangerous megalopolis obsessed with power, glamor, and ceaseless body modification. Recent Reviews: Very Positive (6,845) - 93% of the 6,845 user reviews in the last 30 days are positive.', 0.00, 0.00, '', 5, '2077 Cyberpunk.jpg', '2024-08-24 12:03:06', NULL),
(7, 'a plague tale innocence', '', 'Follow the grim tale of young Amicia and her little brother Hugo, in a heartrending journey through the darkest hours of history. Hunted by Inquisition soldiers and surrounded by unstoppable swarms of rats, Amicia and Hugo will come to know and trust each other.', 0.00, 0.00, '', 6, 'a plague tale innocence.jpg', '2024-08-24 12:03:06', NULL),
(8, 'Assassin\'s Creed I', '', 'The setting is 1191 AD. The Third Crusade is tearing the Holy Land apart. You, Altair, intend to stop the hostilities by suppressing both sides of the conflict. You are an Assassin, a warrior shrouded in secrecy and feared for your ruthlessness.', 0.00, 0.00, '', 1, 'Assassin\'s_Creed-1.jpg', '2024-08-24 12:03:06', NULL),
(9, 'Assassins Creed II', '', 'Assassin\'s Creed 2 is an epic story of family, vengeance and conspiracy set in the pristine, yet brutal, backdrop of a Renaissance Italy. Ezio befriends Leonardo da Vinci, takes on Florence\'s most powerful families and ventures throughout the canals of Venice where he learns to become a master assassin.', 0.00, 0.00, '', 1, 'Assassins_Creed_2.jpg', '2024-08-24 12:03:06', NULL),
(10, 'Assassins Creed III', '', 'This is an action-adventure game in which players assume the role of Desmond, an assassin who must revisit the lives of his ancestors during the American Revolutionary War. Most missions require players to find, stalk, and kill enemies with a variety of weapons (e.g., muskets, handguns, bayonets, tomahawks).', 0.00, 0.00, '', 1, 'Assassin\'s_Creed_3.jpg', '2024-08-24 12:03:06', NULL),
(11, 'Assassin\'s Creed IIII', '', 'Assassin\'s Creed IV: Black Flag is an action-adventure, stealth game set in an open world environment and played from a third-person perspective. The game features three main cities: Havana, Kingston, and Nassau, which reside under Spanish, British, and pirate influence, respectively.', 0.00, 0.00, '', 0, 'Assassin\'s_Creed_4.jpg', '2024-08-24 12:03:06', NULL),
(12, 'Assassin\'s Creed valhalla', '', 'Assassin\'s Creed Valhalla is an action role-playing video game structured around several main story arcs and numerous optional side-missions, called \"World Events\". The player takes on the role of Eivor Varinsdottir (/ˈeɪvɔːr/), a Viking raider, as they lead their fellow Vikings against the Anglo-Saxon kingdoms.', 0.00, 0.00, '', 1, 'assasins-creed-valhalla.jpg', '2024-08-24 12:03:06', NULL),
(13, 'Tomb Raider I', '', 'Tomb Raider is an action-adventure video game in which the player assumes the role of archaeologist-adventurer Lara Croft, who navigates through a series of ancient ruins and tombs in search of an ancient artefact. The game is split into four zones: Peru, Greece, Egypt and the lost continent of Atlantis.', 0.00, 0.00, '', 6, 'Tomb_Raider_(1996).png', '2024-08-24 12:09:18', NULL),
(14, 'Tomb Raider II', '', 'Tomb Raider is an action-adventure video game in which the player assumes the role of archaeologist-adventurer Lara Croft, who navigates through a series of ancient ruins and tombs in search of an ancient artefact. The game is split into four zones: Peru, Greece, Egypt and the lost continent of Atlantis.', 0.00, 0.00, '', 6, 'Tomb_Raider_II.png', '2024-08-24 12:09:18', NULL),
(15, 'Tomb Raider III', '', 'Tomb Raider is an action-adventure video game in which the player assumes the role of archaeologist-adventurer Lara Croft, who navigates through a series of ancient ruins and tombs in search of an ancient artefact. The game is split into four zones: Peru, Greece, Egypt and the lost continent of Atlantis.', 0.00, 0.00, '', 6, 'Tomb_Raider_III.png', '2024-08-24 12:09:18', NULL),
(16, 'Mortal Kombat X', '', 'Mortal Kombat X is a fighting game in which two characters fight against each other using a variety of attacks, including special moves, and the series\' trademark gruesome finishing moves, Fatalities. The game allows two players to face each other (either locally or online), or a single player to play against the CPU.', 0.00, 0.00, '', 2, 'Mortal Kombat-x.jpg', '2024-08-25 11:10:25', NULL),
(17, 'Street Fighter V', 'The game features 3D characters and backgrounds, but is played in a 2D arena. Street Fighter V carries on the 2D fighting gameplay of its predecessors, in which two fighters use a variety of attacks and special abilities to knock out their opponent.', '', 0.00, 0.00, '', 2, 'Street Fighter V.jpg', '2024-08-25 11:10:25', NULL),
(18, 'Tekken 7', '', 'TEKKEN 7 represents the final chapter of the 20-year-long Mishima feud. Unveil the epic ending to the emotionally charged family warfare between the members of the Mishima Clan as they struggle to settle old scores and wrestle for control of a global empire, putting the balance of the world in peril.', 0.00, 0.00, '', 2, 'Tekken.jpg', '2024-08-25 11:10:25', NULL),
(19, 'Mortal Kombat 11', '', 'Like the previous three games in the series, including Mortal Kombat Mobile, Mortal Kombat 11 is a 2.5D fighting game. Alongside the returning Fatalities, Brutalities, Stage Fatalities, Friendships and Quitalities, new gameplay features are introduced, such as Fatal Blows and Krushing Blows.', 0.00, 0.00, '', 2, 'Mortal_Kombat_11.png', '2024-08-25 11:10:25', NULL),
(20, 'Super Smash Bros. Ultimate', '', 'Super Smash Bros. Ultimate is a platform fighter for up to eight players in which characters from Nintendo games and third-party franchises fight to knock each other out of an arena.', 0.00, 0.00, '', 2, 'Super Smash Bros. Ultimate.jpg', '2024-08-25 11:10:25', NULL),
(21, 'Dragon Ball FighterZ ', '', 'DRAGON BALL FighterZ is born from what makes the DRAGON BALL series so loved and famous: endless spectacular fights with its all-powerful fighters. Partnering with Arc System Works, DRAGON BALL FighterZ maximizes high end Anime graphics and brings easy to learn but difficult to master fighting gameplay.', 0.00, 0.00, '', 2, 'Dragon Ball FighterZ.jpg', '2024-08-25 11:10:25', NULL),
(22, 'Soulcalibur VI', '', 'SOULCALIBUR VI represents the latest entry in the premier weapons-based, head-to-head fighting series and continues the epic struggle of warriors searching for the legendary Soul Swords. The heroic battles transpire in a beautiful and fluid world, with eye-popping graphics and visual appeal.', 0.00, 0.00, '', 2, 'Soulcalibur VI.jpg', '2024-08-25 11:10:25', NULL),
(23, 'Guilty Gear Strive', '', 'New Revolution in Fighting Games!\r\nGuilty Gear -Strive- brings a number of new and innovative gameplay mechanics designed to allow players new to the series to quickly learn the fundamentals while maintaining the deep, creative gameplay Guilty Gear is praised for.', 0.00, 0.00, '', 2, 'Guilty Gear Strive.jpg', '2024-08-25 11:10:25', NULL),
(24, 'Injustice 2', '', 'Injustice 2\'s storyline centers around Batman and his insurgency\'s attempt to restore society after the fall of Superman\'s Regime; however, the arrivals of the newly formed supervillain group \"The Society\" and the alien Brainiac force Batman to consider freeing the imprisoned Superman to help combat the threats.', 0.00, 0.00, '', 2, 'Injustice 2.jpg', '2024-08-25 11:10:25', NULL),
(25, 'BlazBlue Central Fiction', '', 'Aksys Games Localization, Inc. This is a fighting game in which players engage in contests of strength while following a multiple-character storyline. Characters mostly punch and kick each other in an attempt to drain opponents\' health meters.', 0.00, 0.00, '', 2, 'BlazBlue Central Fiction.jpg', '2024-08-25 11:10:25', NULL),
(26, 'evelmaycry3', '', '', 0.00, 0.00, '', 1, 'evelmaycry3.jpg', '2024-08-25 11:34:49', NULL),
(30, 'Destiny 2', '', 'Set in a \"mythic science fiction\" world, the game features a multiplayer \"shared-world\" environment with elements of role-playing games. Like the original, activities in Destiny 2 are divided among player versus environment (PvE) and player versus player (PvP) game types.', 0.00, 0.00, '', 5, 'Destiny_2.jpg', '2024-08-26 10:33:25', NULL),
(31, 'DOOM Eternal', '', 'Set some time after the events of the 2016 game, the story follows the Doom Slayer once again, on a mission to end Hell\'s consumption of Earth and foil the alien Khan Maykr\'s plans to exterminate humanity. Along with the single-player campaign, a multiplayer mode, Battlemode, was introduced.', 0.00, 0.00, '', 5, 'DOOM Eternal.png', '2024-08-26 10:36:13', NULL),
(32, 'Escape from Tarkov', '', 'Escape from Tarkov is a story-based experience that challenges all comers to escape the city with their lives. Matches are session-based and inhabited not only by human players but AI-driven Scavs to fill the world – ensuring a constant air of danger.', 0.00, 0.00, '', 5, 'Escape from Tarkov.jpg', '2024-08-26 10:36:13', NULL),
(33, 'Fortnite', '', 'Fortnite is a third-person shooter game where up to 100 players compete to be the last person or team standing. You can compete alone or join a team of up to four. You progress through the game by exploring the island, collecting weapons, building fortifications and engaging in combat with other players.', 0.00, 0.00, '', 5, 'Fortnite.jpg', '2024-08-26 10:38:47', NULL),
(34, 'Rainbow Six', '', 'Tom Clancy\'s Rainbow Six® Siege is an elite, realistic, tactical, team-based shooter where superior planning and execution triumph. It features 5v5 attack vs. defense gameplay and intense close-quarters combat in destructible environments.', 0.00, 0.00, '', 5, 'Rainbow Six Siege.jpg', '2024-08-26 10:38:47', NULL),
(35, 'The Legend of Zelda: Tears of the Kingdom', '', 'The Legend of Zelda: Tears of the Kingdom[b] is a 2023 action-adventure game developed and published by Nintendo for the Nintendo Switch. The player controls Link as he searches for Princess Zelda and fights to prevent Ganondorf from destroying Hyrule. Tears of the Kingdom retains the open-world gameplay and setting of its predecessor, Breath of the Wild (2017), and features new environments, including an area composed of floating islands in the sky and an underground area beneath Hyrule known as the Depths. The player has access to various devices that aid in combat or exploration and can be used to construct vehicles.\r\n\r\nTears of the Kingdom was conceived after ideas for Breath of the Wild downloadable content had exceeded its scope. Development was led by Nintendo\'s Entertainment Planning & Development division, with Breath of the Wild director Hidemaro Fujibayashi and producer Eiji Aonuma reprising their roles. The developers were inspired by social media posts to create gameplay mechanics that encouraged experimentation and sometimes struggled to differentiate the sequel from its predecessor. A teaser was shown at E3 2019, while a full reveal featuring gameplay was shown at E3 2021. Tears of the Kingdom was originally planned for release in 2022, but was delayed until May 2023 to allow the developers to refine it.\r\n\r\nTears of the Kingdom received critical acclaim, with critics praising the expanded world, new powers, scale, and story, while criticism focused on its voice acting and technical performance. It sold more than 10 million copies in its first three days of release and over 20.80 million copies by June 2024, making it the ninth-best-selling game on the Nintendo Switch.', 0.00, 0.00, '', 1, 'The Legend of Zelda Tears of the Kingdom.jpg', '2024-08-26 10:55:03', NULL),
(36, 'God of War', '', 'It is the ninth installment in the series, the ninth chronologically, and the sequel to 2018\'s God of War. Loosely based on Norse mythology, the game is set in ancient Scandinavia and features series protagonist, Kratos, and his now teenage son, Atreus.', 0.00, 0.00, '', 1, 'God_of_War_Ragnarök_cover.jpg', '2024-08-26 10:59:47', NULL),
(37, 'Elden Ring', '', 'Elden Ring takes place in the Lands Between, a realm blessed by entities called outer gods. Most prominent is the Greater Will, who sent down the Elden Ring – a collection of magical runes that govern the land\'s physics – and the Erdtree – an enormous, golden tree that empowers the inhabitants.', 0.00, 0.00, '', 1, 'Elden Ring.jpg', '2024-08-26 10:59:47', NULL),
(38, 'Miles Morales Spider-Man', '', 'Miles Morales Spider-Man\r\nGifted with web-shooters and guided by Peter Parker, Miles Morales uses his abilities to be a different kind of Spider-Man. In the alternate reality of Earth-1610, a young New York City teen was bitten by a genetically enhanced spider.', 0.00, 0.00, '', 1, 'Marvel’s Spider Man Miles Morales.jpg', '2024-08-26 10:59:47', NULL),
(39, 'Ghost of Tsushima ', '', 'Ghost of Tsushima is a 2020 action-adventure game developed by Sucker Punch Productions and published by Sony Interactive Entertainment. The player controls Jin Sakai, a samurai on a quest to protect Tsushima Island during the first Mongol invasion of Japan.', 0.00, 0.00, '', 1, 'Ghost_of_Tsushima.jpg', '2024-08-26 10:59:47', NULL),
(40, 'Horizon Forbidden ', '', 'Synopsis. Horizon Forbidden West continues the story of Aloy half a year after the events of the Zero Dawn, a young huntress of the Nora tribe sent on a quest to a mysterious frontier spanning Utah to the Pacific coast to find the source of a mysterious plague that kills all it infects.', 0.00, 0.00, '', 1, 'Games-Horizon-Forbidden-West-Review-top.jpg', '2024-08-26 10:59:47', NULL),
(41, 'Forza Horizon 5', '', 'Forza Horizon 5 is a 2021 racing video game developed by Playground Games and published by Xbox Game Studios. It is the fifth Forza Horizon title and twelfth main instalment in the Forza series. The game is set in a fictionalised representation of Mexico.', 0.00, 0.00, '', 3, 'forza-horizon.jpg', '2024-08-26 11:10:13', NULL),
(42, 'Gran Turismo 7', '', 'Gran Turismo 7 shines a spotlight on the long history of cars and their culture as the player embarks on a journey to collect the most historic examples. The game is designed to allow players to learn about the origins of each model and their place in history naturally as the game progresses.', 0.00, 0.00, '', 3, 'Gran Turismo 7.jpg', '2024-08-26 11:10:13', NULL),
(43, 'Mario Kart 8 Deluxe', '', 'It was rereleased on the Nintendo Switch in April 2017 as Mario Kart 8 Deluxe. Deluxe includes all the original DLC, as well as a revamped battle mode and other gameplay alterations. In February 2022, a new DLC, the Booster Course Pass, was announced, in which 48 new circuits and 8 characters were added progressively.', 0.00, 0.00, '', 3, 'Mario Kart 8 Deluxe.jpg', '2024-08-26 11:10:13', NULL),
(44, 'F1 23', '', 'F1 23 features overhauled driving physics and added the option to set a 35% race distance. Red flags, which last appeared in F1 2014, make an appearance. The game\'s UI has been overhauled for an experience much more akin to the presentation of current Formula One races.', 0.00, 0.00, '', 3, 'f1.jpg', '2024-08-26 11:10:13', NULL),
(45, 'Need for Speed Unbound', '', 'Need for Speed Unbound is a racing game set in a fictional city called Lakeshore City, which is based on Chicago. It features an open world environment and gameplay similar to that of previous entries in the series, being mainly focused around street racing.', 0.00, 0.00, '', 3, 'Need for Speed Unbound.png', '2024-08-26 11:10:13', NULL),
(46, 'DIRT 5', '', 'DIRT 5 is a fun, amplified, off-road arcade racing experience created by Codemasters. Blaze a trail on routes across the world, covering gravel, ice, snow and sand, with a roster of cars ranging from rally icons to trucks, to GT heroes.', 0.00, 0.00, '', 3, 'DIRT 5.jpg', '2024-08-26 11:10:13', NULL),
(47, 'Assetto Corsa Competizione', '', 'Assetto Corsa Competizione is designed to faithfully recreate the performance and the driving experience of real GT World Challenge cars through a sophisticated mathematical model that accurately replicates tyre grip, aerodynamic impact, engine parameters, suspensions and electronics systems that determine vehicle ...', 0.00, 0.00, '', 3, 'Assetto Corsa Competizione.jpg', '2024-08-26 11:10:13', NULL),
(48, 'Wreckfest', '', 'Summary Wreckfest is a demolition derby themed racing game with soft-body damage modeling, sophisticated driving dynamics and in-depth vehicle upgrading, featuring both demolition derbies and more traditional track races. It\'s all about fun, breakneck racing and over-the-top crashes. Platforms: PC.', 0.00, 0.00, '', 3, 'Wreckfest.jpg', '2024-08-26 11:10:13', NULL),
(49, 'Project CARS 3', '', 'Project CARS 3 introduces more customizable cars that are available to race over 140 global circuits. The game also features 24-hour cycles, various seasons, and weather effects. The career mode has been rebuilt, with the artificial intelligence being enhanced. The game also support VR on PC.', 0.00, 0.00, '', 3, 'Project CARS 3.jpg', '2024-08-26 11:10:13', NULL),
(50, 'Hot Wheels Unleashed', '', 'Hot Wheels Unleashed - Wikipedia\r\nHot Wheels Unleashed is a racing game played from a third-person perspective. In the game, the player assumes control of vehicles from the Hot Wheels franchise, and races against other opponents in miniature tracks set in various everyday locations and environments, such as a garage, kitchen, and bedroom.', 0.00, 0.00, '', 3, 'Hot Wheels Unleashed.jpeg', '2024-08-26 11:10:13', NULL),
(51, 'FIFA 23', '', 'FIFA 23 features the men\'s World Cup game mode and the women\'s World Cup game mode, replicating the 2022 FIFA World Cup and the 2023 FIFA Women\'s World Cup. This is the only title in the series to feature both World Cups as special modes.', 0.00, 0.00, '', 4, 'FIFA 23.jpg', '2024-08-27 11:50:15', NULL),
(52, 'NBA 2K24 ', '', 'Enjoy loads of pure, unadulterated action and limitless personalized MyPLAYER options in MyCAREER. Collect an impressive array of legends and build your perfect lineup in MyTEAM. Feel more responsive gameplay and polished visuals while playing with your favorite NBA and WNBA teams in PLAY NOW.', 0.00, 0.00, '', 4, 'NBA 2K24.jpg', '2024-08-27 11:50:15', NULL),
(53, 'Madden NFL 24', '', 'Gameplay. Madden NFL 24 introduces exclusive next gen features, including SAPIEN technology, which allows for more realistic movement and more lifelike player models. Gameplay includes the return of refs to the field, improved blocking and Fieldsense.', 0.00, 0.00, 'madden.jpg', 4, 'madden.jpg', '2024-08-27 11:50:15', NULL),
(54, 'MLB The Show 23', '', 'MLB The Show 23 is a baseball simulation video game developed by San Diego Studio and published by Sony Interactive Entertainment. It offers realistic gameplay, advanced graphics, and immersive features that bring the sport to life. The game includes multiple modes, including Road to the Show and Diamond Dynasty, allowing players to create their own players, build teams, and compete online. MLB The Show 23 also features updated rosters, stadiums, and improved AI, making it one of the most comprehensive baseball games available.', 0.00, 0.00, '', 4, 'MLB The Show 23.jpg', '2024-08-27 11:50:15', NULL),
(55, 'Football Manager 2024', '', 'FM24 is filled with new additions that deepen the immersion and elevate your gameplay experience with upgrades to set pieces, man management, squad building, Matchday and much more. Start a new story or import your existing career from FM23 - the choice is yours.', 0.00, 0.00, '', 4, 'Football Manager 2024.jpg', '2024-08-27 11:50:15', NULL),
(56, 'Tony Hawk\'s Pro Skater', '', 'Tony Hawk\'s Pro Skater 1 + 2 is a skateboarding video game played in a third-person view with its gameplay oriented towards classic arcade games. The goal of most modes of the game is to achieve a high score or collect certain objects. The player must complete objectives to unlock levels to progress through the game.', 0.00, 0.00, '', 4, 'Tony Hawk\'s Pro Skater.jpg', '2024-08-27 11:50:15', NULL),
(57, 'WWE 2K23', '', 'WWE 2K23 is a 2023 professional wrestling sports video game developed by Visual Concepts and published by 2K. It is the twenty-third overall installment of the video game series based on WWE, the ninth game under the WWE 2K banner, and the successor to WWE 2K22.', 0.00, 0.00, '', 4, 'WWE 2K23.jpg', '2024-08-27 11:50:15', NULL),
(58, 'eFootball 2024', '', 'eFootball 2024 is the latest installment in Konami\'s football simulation series, building on the free-to-play model with enhanced graphics, realistic gameplay, and updated player rosters. The game offers various modes, including online multiplayer and events, catering to both casual players and competitive esports enthusiasts. New features include improved AI, refined controls, and more immersive stadium atmospheres. The focus remains on delivering an authentic football experience with regular updates reflecting real-world changes in teams and players. It\'s available on multiple platforms, including consoles, PC, and mobile devices.', 0.00, 0.00, '', 4, 'eFootball.jpg', '2024-08-27 11:50:15', NULL),
(59, 'PGA Tour 2K23', '', 'PGA Tour 2K23 takes an already excellent golfing simulator and builds upon it, making it better and more fleshed out by adding things that were sorely needed. We\'re still waiting for properly glamourous careers and tournaments but the gameplay itself will spellbind every golf fan.', 0.00, 0.00, '', 4, 'PGA Tour 2K23.jpg', '2024-08-27 11:50:15', NULL),
(60, 'NHL 24', '', 'NHL 24 simulates the thrill and intensity of a professional NHL hockey game. Available on both Xbox and Playstation, players can either play as or against one of NHL\'s professional teams and test their skills on the virtual ice.', 0.00, 0.00, '', 4, 'NHL.jpg', '2024-08-27 11:50:15', NULL),
(61, 'GTA 5', '', 'When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government and the entertainment industry, they must pull off a series of dangerous heists to survive in a ruthless city ...', 0.00, 0.00, '', 6, 'GTA5.jpg', '2024-08-27 11:53:58', NULL),
(62, '', '', '', 0.00, 0.00, '', 0, 'https://placehold.co/500x500', '2024-08-27 11:53:58', NULL),
(63, 'Firewatch', '', 'Firewatch is a single-player first-person mystery set in the Wyoming wilderness. The year is 1989. You are a man named Henry who has retreated from his messy life to work as a fire lookout in the Wyoming wilderness. Perched high atop a mountain, it\'s your job to look for smoke and keep the wilderness safe.', 0.00, 0.00, '', 6, 'Firewatch.jpg', '2024-08-27 11:55:44', NULL),
(64, 'Life is Strange', '', 'Life is Strange is an award-winning and critically acclaimed episodic adventure game that allows the player to rewind time and affect the past, present and future. Follow the story of Max Caulfield, a photography senior who discovers she can rewind time while saving her best friend Chloe Price.', 0.00, 0.00, '', 6, 'Life is Strange.jpg', '2024-08-27 11:57:24', NULL),
(65, 'Uncharted 4', '', 'On the hunt for Captain Henry Avery\'s long-lost treasure, Sam and Drake set off to find Libertalia, the pirate utopia deep in the forests of Madagascar. UNCHARTED 4: A Thief\'s End takes players on a journey around the globe, through jungle isles, far-flung cities and snow-capped peaks on the search for Avery\'s fortune.', 0.00, 0.00, '', 6, 'Uncharted 4 A Thief\'s End.jpg', '2024-08-27 11:59:50', NULL),
(66, 'The Witcher 3: Wild Hunt', '', 'The game takes place in a fictional fantasy world based on Slavic mythology. Players control Geralt of Rivia, a monster slayer for hire known as a Witcher, and search for his adopted daughter, who is on the run from the otherworldly Wild Hunt.', 0.00, 0.00, '', 6, 'The Witcher.jpg', '2024-08-27 12:02:06', NULL),
(67, 'Tomb Raider 2013', '', 'Tomb Raider explores the intense and gritty origin story of Lara Croft and her ascent from a young woman to a hardened survivor. Armed only with raw instincts and the ability to push beyond the limits of human endurance, Lara must fight to unravel the dark history of a forgotten island to escape its relentless hold.', 0.00, 0.00, '', 6, 'tompraider-2013.jpg', '2024-08-27 12:03:17', NULL),
(68, 'Far Cry 6', '', 'Plot. Far Cry 6 takes place in 2021 in Yara, a fictional Caribbean island nation inspired by Cuba and ruled by the dictator Antón Castillo (Giancarlo Esposito). In 1967 a guerrilla revolution topples the presidency of Antón\'s father, leading to Yara\'s isolation from the rest of the world.', 0.00, 0.00, '', 6, 'farcry.jpg', '2024-08-27 12:05:55', NULL);

--
-- Indexen voor geëxporteerde tabellen
--

--
-- Indexen voor tabel `games`
--
ALTER TABLE `games`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT voor geëxporteerde tabellen
--

--
-- AUTO_INCREMENT voor een tabel `games`
--
ALTER TABLE `games`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=69;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
